### ISSUE TITLE
Error in names(simlist) <- simnames

### ISSUE THREAD

**Issue by aimirza** [himelmallick/BenchmarkMicrobiome#1]
Very cool project!

I had to remove the forward slash in `'/Library/sparseDOSSAhelperFunctions.R'` from line 106 of the file Load_Simulator.R to remove the error:

```
Error in file(filename, "r", encoding = encoding) :
  cannot open the connection
Calls: <Anonymous> -> sourceURL -> source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/Library/sparseDOSSAhelperFunctions.R': No such file or directory
Execution halted 
```
However I get the following error after running the code: 
`Rscript Codes/Load_Simulator.R --metadataType UVB --nSubjects 5 --nPerSubject 1 --nMicrobes 10 --spikeMicrobes 0.1 --nMetadata 1 --spikeMetadata 1 --effectSize 20 --workingDirectory ~/BenchmarkMicrobiome/`

```
Error in names(simlist) <- simnames :
  'names' attribute [100] must be the same length as the vector [78]
Calls: trigger_sparseDOSSA_Simulator
Execution halted
```

**Comment by aimirza** [comment]
It worked after I changed `-nMicrobes `to 100

**Comment by himelmallick** [comment]
Thanks for trying it out. Please feel free to let me know if you come across any other issues.
